featured :sparkles: criação da seção 1
paq-devs/site-paq pull request #1
Opened 2024-06-04 21:46 UTC by PedroRocha2

2024-06-18 16:54 UTC, PedroRocha2 commented
Criação da navbar concluida e começo de uma seção 3

2024-06-20 00:02 UTC, thcerutti requested changes
@PedroRocha2 apontei algumas sugestões de melhoria no seu PR, na próxima mentoria podemos falar a respeito 😉

2024-06-20 00:02 UTC, thcerutti commented on public/BG.png
Este arquivo não está mais sendo utilizado, pode ser excluído

2024-06-20 00:02 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
> +        <Section1 />
Para melhor identificar as seções, seria mais adequado darmos nomes mais sigestivos aos componentes. Quando alguém olhar para estes componentes, ou mesmo nós mesmos no futuro, Não saberemos do que se trata vendo um código:

```js
<Section1 />
<Section2 />
```
Teríamos que entrar em cada componente para ter certeza do que se trata. Para solucionar isso podemos renomear os componentes da seguinte forma:

- `Section1 -> PaqHeader`
- `Section 2 -> ConectarETransformar`

2024-06-20 00:02 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
Como cada seção será um componente separado, faz sentido ela estar logo dentro da pasta `/components`

2024-06-20 00:02 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
> +    return (<div>
aqui não precisamos utilizar uma `<div>`, podemos utilizar um `fragment` ([doc](https://pt-br.react.dev/reference/react/Fragment)) que é um padrão utilizado profissionalmente com React

2024-06-20 00:02 UTC, thcerutti commented on src/app/components/(landing)/section2.tsx
> +            <div>
não precisamos desta `<div>` interna, podemos manter somente a hierarquia `div > h1`

2024-06-20 20:21 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
legal mas vou deixar assim

2024-06-20 20:22 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
> +    return (<div>
done

2024-06-20 20:31 UTC, thcerutti approved these changes

2024-06-20 20:31 UTC, merged