Sessão Junto com a gente
paq-devs/site-paq pull request #16
Opened 2024-07-27 06:54 UTC by PedroRocha2

# Sessão junto com a gente

## Descrição
criação da sessão junto com a gente, que visa mostrar nossos apoiadores e parceiros do paq, juntamente com um botão para fazer parte do time. Possui 3 cards de parceiros, apoiadores e parceiros educacionais, foi feito utilizando css vanila para melhor manipulação de estilos de texto e tailwindcss para melhor produção de responsividade do posicionamento dos elementos, vale lembrar que ja está de maneira responsiva conforme o figma.

## Mudanças
-  criação dos cards de parceiros responsivos
-  Titulo juntamente com imagens separadas em pastas especificas

## Como testar
1. Faça o checkout para a branch do PR:
   ```bash
   git checkout junto-com

2024-07-28 14:03 UTC, thcerutti requested changes

2024-07-28 14:03 UTC, thcerutti commented on src/app/components/JuntoComAGente/cardEducacional.tsx
> +const imagesBottom = [
aqui precisamos alterar a ordem conforme o Figma: Rockerseat, Lab 365, FullCycle

2024-07-28 14:03 UTC, thcerutti commented on src/app/components/JuntoComAGente/JuntoComAGente.tsx
> +            <h2 className='corpo'><span className='font-bold'>Junto com a gente</span> <br /> nessa missão!</h2>
aqui precisamos de um margin-top acima do H2 pra ficar parecido com o Figma:

![image](https://github.com/user-attachments/assets/3456f30f-80ce-40b8-bec9-d85f6dd366af)

2024-07-29 03:01 UTC, PedroRocha2 commented on src/app/components/JuntoComAGente/cardEducacional.tsx
> +const imagesBottom = [
corrigido!

2024-07-29 03:05 UTC, PedroRocha2 commented on src/app/components/JuntoComAGente/JuntoComAGente.tsx
> +            <h2 className='corpo'><span className='font-bold'>Junto com a gente</span> <br /> nessa missão!</h2>
resolvido, adicionei a mclasse my-52 do tailwind para fazer uma margin no eixo Y

2024-07-30 00:26 UTC, thcerutti approved these changes

2024-07-30 00:26 UTC, merged