Como fazer parte
paq-devs/site-paq pull request #17
Opened 2024-07-28 00:56 UTC by PedroRocha2

2024-07-28 13:30 UTC, thcerutti requested changes
@PedroRocha2 identifiquei umas necessidades de mudança nas seções, qualquer dúvida me avise 😉

2024-07-28 13:30 UTC, thcerutti commented on src/app/components/JuntoComAGente/JuntoComAGente.css
Na versão pra mobile falta a borda azul no card:

![image](https://github.com/user-attachments/assets/8863857a-89da-4a74-8ff4-f7b879f382a4)

O tamanhop da fonte está menor que no protótipo e o conteúdo do botão precisa ser corrigido.

2024-07-28 13:30 UTC, thcerutti commented on src/app/components/comoFazerParte/CardVenhaFazerParte.tsx
Assim que o componente é carregado não esixte estado disponível e por isso nenhum card é exibido. Nesse caso seria interessante por padrão já carregarmos o primeiro card e assim que os demais botões são clicados, carrega os outros cards.

![image](https://github.com/user-attachments/assets/a513186a-807b-4b8e-8282-bf0e707e0524)

2024-07-28 13:30 UTC, thcerutti commented on src/app/components/comoFazerParte/CardVenhaFazerParte.css
Precisamos colocar uma margem acima do título pra não ficar assim colado no topo:

![image](https://github.com/user-attachments/assets/9b2980ce-d37b-4bde-b9f4-206ca5ec15f7)

2024-07-29 02:49 UTC, PedroRocha2 commented on src/app/components/JuntoComAGente/JuntoComAGente.css
Opa cerutti, aumentei os tamanhos das fontes, até segunda feira o evanz me da as imagens dos outros cards de mentor e de voluntári. Sobre  o conteudo do botão é esse mesmo que eu coloquei, o do protótipo está errado
e por ultimo sobre a borda eu não mexi em nada e ela apareceu aqui na minha máquina, n fiz nenhuma alteração na classe
![image](https://github.com/user-attachments/assets/c92f2c4a-5a62-4800-b524-0bd850b01de0)

2024-07-29 02:54 UTC, PedroRocha2 commented on src/app/components/comoFazerParte/CardVenhaFazerParte.css
resolvido, era problema do tamanho da font quando expremida

2024-07-29 02:55 UTC, PedroRocha2 commented on src/app/components/comoFazerParte/CardVenhaFazerParte.tsx
![image](https://github.com/user-attachments/assets/7bb00326-a32c-4899-ad2e-1edb0f9d12e1)
resolvi dessa forma, ao invés de passar useState como nulo inicialmente ja atribui o valo 1

2024-07-30 00:52 UTC, thcerutti approved these changes

2024-07-30 00:52 UTC, merged