Feature/contact
paq-devs/site-paq pull request #20
Opened 2024-07-30 12:49 UTC by nicolassps

2024-07-30 14:44 UTC, thcerutti requested changes
Fala @nicolassps , tudo certo? Testei a sua branch aqui na minha máquina e tá ótimo 👏🏻 
Só deixei duas change requests pra ficar tudo redondinho, depois disso já mergeamos e colocamos em staging 😉

2024-07-30 14:44 UTC, thcerutti commented on src/app/components/Contact/adapter/ContactAdapter.ts
> +            "key": process.env.MAILCHIMP_API_KEY,
Como essas env vars serão necessárias quando colocarmos o site em prod, acho que seria interessante documentarmos no Readme.md sobre a necessidade delas informando somente a chave que deve ser usada e omitindo o valor.

2024-07-30 14:44 UTC, thcerutti commented on src/app/components/Contact/Contact.tsx
> +                    <p className="mt-4 sm:w-full text-center text-sm text-gray-600 contact-subtitle">{Language.getOrDefault('contact.subtitle')}</p>
aqui na versão mobile o texto não está usando todo o width conforme o Figma, testei aqui colocando explicitamente o width pra 100% do container (sugestão) e deu certo:

![image](https://github.com/user-attachments/assets/98528eaf-b1fe-4c24-ae9a-682a337bf3bb)

2024-07-30 17:54 UTC, nicolassps commented on src/app/components/Contact/Contact.tsx
> +                    <p className="mt-4 sm:w-full text-center text-sm text-gray-600 contact-subtitle">{Language.getOrDefault('contact.subtitle')}</p>
Boa, vou arrumar

2024-07-31 12:14 UTC, thcerutti approved these changes

2024-07-31 12:14 UTC, thcerutti commented
LGTM 🚀

2024-07-31 12:15 UTC, merged