Finalizado carrossel
paq-devs/site-paq pull request #36
Opened 2024-09-06 20:28 UTC by iofme

2024-09-08 14:38 UTC, thcerutti requested changes

2024-09-08 14:38 UTC, thcerutti commented on src/app/(Site)/(LandingPage)/page.tsx
> +      <Depoimentos />
Ao descomentar todas as seções tá rolando conflito de estilos 🥲 vou ver se consigo resolver por aqui

![image](https://github.com/user-attachments/assets/a250fabe-fc61-4a55-8c63-fce62f9ac66a)

2024-09-08 14:38 UTC, thcerutti commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/app/components/comoFazerParte/ButtonCard.jsx", "src/app/components/comoFazerParte/ButtonCard.jsx", "src/app/component
Precisamos destas adições de componentes neste arquivo de configuração?

2024-09-08 14:38 UTC, thcerutti commented on src/app/globals.css
> +@import url("./components/Depoimentos/CardDepoimento.module.css");
conceitualmente não devemos incluir um estilo de css específico em um arquivo global, talvez esse seja o motivo do conflito de estilos que tá rolando nesse PR 🤔

2024-09-08 14:38 UTC, thcerutti commented on src/app/components/Depoimentos/cards.ts
> +const depoimentos = [
esses depoimentos parecem estar duplicados com o arquivo `src/app/components/Depoimentos/depoimentos.json`, se este objeto ou arquivo não está sendo usado podemos apagar pra limpar o código.

2024-09-08 14:38 UTC, thcerutti commented on src/app/(Site)/layout.tsx
> +import "../globals.css"
esse arquivo global.css já é importado de forma automática, não precisamos importar ele explicitamente aqui

2024-09-08 19:38 UTC, thcerutti commented
@iofme subi um commit com alteraçõs que pelo que vi aqui corrigiram o problema. Pfv dê um `git pull` aí e testa pra ver se tá tudo ok agora com os estilos do carrossel 😉

2024-09-09 18:17 UTC, iofme commented on src/app/components/Depoimentos/cards.ts
> +const depoimentos = [
Removi o Json

2024-09-09 18:18 UTC, iofme commented on src/app/globals.css
> +@import url("./components/Depoimentos/CardDepoimento.module.css");
hummmmmm, tava vendo um curso de front e vi que importavam os css da global

2024-09-09 18:19 UTC, iofme commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "src/app/components/comoFazerParte/ButtonCard.jsx", "src/app/components/comoFazerParte/ButtonCard.jsx", "src/app/component
Tinha lido que era para ter mais performasse na imagem

2024-09-09 18:20 UTC, iofme commented on src/app/(Site)/(LandingPage)/page.tsx
> +      <Depoimentos />
Vi que é a sessão "Nosso time"

2024-09-09 18:20 UTC, iofme commented on src/app/(Site)/layout.tsx
> +import "../globals.css"
Certo

2024-09-10 00:17 UTC, thcerutti approved these changes

2024-09-10 00:17 UTC, merged